# docker run --name some-nginx -v /some/content:/usr/content:/usr/share/nginx/html:ro -d nginx
services:
  web:
    image: nginx
    # container_name: some-nginx
    volumes: 
      - "/home/content:/usr/share/nginx/html:ro"